### PR TITLE
angular.lowercase method removed in angular 1.7 

### PR DESCRIPTION
**Pull request by cedricbonhomme**
https://github.com/angular/angular.js/blob/v1.7.0-rc.0/CHANGELOG.md

The helper functions angular.lowercase and angular.uppercase have been removed.

### CODE REVIEW

**Comment by cedricbonhomme** [comment]
Dear Oscar,
Could you provide a feedback if you plan to merge the pull request?
Cheers,

**Comment by OscarYuen** [comment]
@cedricbonhomme Thanks for contribution. Your PR is merged :)

**Comment by cedricbonhomme** [comment]
thank you!

**Comment by cedricbonhomme** [comment]
will you publish the release on npmjs.com ?

**Comment by OscarYuen** [comment]
@cedricbonhomme Sure, I would do it asap

**Comment by cedricbonhomme** [comment]
Cool, thank you very much!

**Comment by OscarYuen** [comment]
@cedricbonhomme Already published the version. Sorry for being late:)

**Comment by cedricbonhomme** [comment]
thank you!

**Pull request merged**
